services:

  services:

   server:
    build:
            context: .
            dockerfile: ./automation/docker/Dockerfile
    container_name: server
    volumes:
            - ./:/var/www/html
    links:
            - database
    ports:
       - "${BACKEND_PORT:-81}:80"


  dev:
    image: bricefa5052/symfony-7-docker-wsl:latest
    command: sleep infinity
    volumes:
      - ../.:/workspace
    ports:
      - "${BACKEND_PORT:-8000}:80"
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DATABASE:-app}"
      MAILER_DSN: "smtp://mailer:1025"
      
  database:
    image: mysql:${MYSQL_VERSION:-8}-oracle
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      # changer le mot de passe en production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!RootChangeMe!}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw

  phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            - PMA_HOST=${DB_HOST:-database}
            - PMA_USER=${DB_USER:-admin}
            - PMA_PASSWORD=${DB_PASSWORD:-Afpa1234}
        links:
            - database
        ports:
            - 8090:80

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database_data:


