<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMx9jYL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMx9jYL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNMx9jYL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNMx9jYL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNMx9jYL\App_KernelDevDebugContainer([
    'container.build_hash' => 'NMx9jYL',
    'container.build_id' => '909b0a05',
    'container.build_time' => 1731530941,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMx9jYL');
