<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJkLKdXr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJkLKdXr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJkLKdXr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJkLKdXr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJkLKdXr\App_KernelDevDebugContainer([
    'container.build_hash' => 'JkLKdXr',
    'container.build_id' => 'c64fb794',
    'container.build_time' => 1730057017,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJkLKdXr');
